export const INITIAL_SERVICES = [
  {
    id: 1,
    name: "Plumbing Repair",
    category: "Plumbing",
    subCategory: "Pipe Fix",
    pricing: "50 LE / Hour",
    pricingType: "Hourly",
    price: "50",
    active: true,
    approved: true,
    hasActiveBookings: false,
    serviceImage: "plumber.jpg",
    alwaysAvailable: true,
    description: "Expert plumbing services for homes and offices.",
    gallery: ["plumbing1.jpg", "plumbing2.jpg"],
  },
  {
    id: 2,
    name: "AC Installation",
    category: "Electrical",
    subCategory: "Installation",
    pricing: "300 LE",
    pricingType: "Fixed",
    price: "300",
    active: true,
    approved: true,
    hasActiveBookings: true,
    serviceImage: "ac.jpg",
    alwaysAvailable: false,
    description: "Professional AC installation and maintenance.",
    gallery: ["ac1.jpg"],
  },
  {
    id: 3,
    name: "Deep Cleaning",
    category: "Cleaning",
    subCategory: "Home Cleaning",
    pricing: "20 LE / Hour",
    pricingType: "Hourly",
    price: "20",
    active: false,
    approved: true,
    hasActiveBookings: false,
    serviceImage: "cleaning.jpg",
    alwaysAvailable: true,
    description: "Thorough cleaning for your home.",
    gallery: [],
  },
  {
    id: 4,
    name: "Painting",
    category: "Painting",
    subCategory: "Interior",
    pricing: "150 LE",
    pricingType: "Fixed",
    price: "150",
    active: true,
    approved: true,
    hasActiveBookings: false,
    serviceImage: "painting.jpg",
    alwaysAvailable: true,
    description: "High-quality interior painting.",
    gallery: ["paint1.jpg"],
  },
];