export const pendingProvidersMock = [
  {
    users_id: 1,
    full_name: "Ahmed Hassan",
    email: "ahmed@example.com",
    phone_number: "01012345678",
    address: "Nasr City",
    city: "Cairo",
    created_at: "2026-03-20",
    account_status: "pending",
    category: "Cleaning",
    subcategory: "Home Cleaning",
    service_name: "Deep Cleaning",
    price: "150 EGP",
    description: "Professional home cleaning service"
  },
  {
    users_id: 2,
    full_name: "Sara Mohamed",
    email: "sara@example.com",
    phone_number: "01198765432",
    address: "Dokki",
    city: "Giza",
    created_at: "2026-03-21",
    account_status: "pending",
    category: "Maintenance",
    subcategory: "Electrical",
    service_name: "Wiring Fix",
    price: "200 EGP",
    description: "Fix electrical issues safely"
  },
  {
    users_id: 3,
    full_name: "Mohamed Ali",
    email: "[EMAIL_ADDRESS]",
    phone_number: "01234567890",
    address: "Maadi",
    city: "Cairo",
    created_at: "2026-03-22",
    account_status: "pending",
    category: "Cleaning",
    subcategory: "Home Cleaning",
    service_name: "Deep Cleaning",
    price: "150 EGP",
    description: "Professional home cleaning service"
  },
  {
    users_id: 4,
    full_name: "Mohamed Ali",
    email: "[EMAIL_ADDRESS]",
    phone_number: "01234567890",
    address: "Maadi",
    city: "Cairo",
    created_at: "2026-03-22",
    account_status: "pending",
    category: "Cleaning",
    subcategory: "Home Cleaning",
    service_name: "Deep Cleaning",
    price: "150 EGP",
    description: "Professional home cleaning service"
  },
  {
    users_id: 5,
    full_name: "Mohamed Ali",
    email: "[EMAIL_ADDRESS]",
    phone_number: "01234567890",
    address: "Maadi",
    city: "Cairo",
    created_at: "2026-03-22",
    account_status: "pending",
    category: "Cleaning",
    subcategory: "Home Cleaning",
    service_name: "Deep Cleaning",
    price: "150 EGP",
    description: "Professional home cleaning service"
  },
  {
    users_id: 6,
    full_name: "Mohamed Ali",
    email: "[EMAIL_ADDRESS]",
    phone_number: "01234567890",
    address: "Maadi",
    city: "Cairo",
    created_at: "2026-03-22",
    account_status: "pending",
    category: "Cleaning",
    subcategory: "Home Cleaning",
    service_name: "Deep Cleaning",
    price: "150 EGP",
    description: "Professional home cleaning service"
  }
];